export const ENVIROMENT = {
  // Project
  HOST: import.meta.env.HOST,

  // Authentication
  LOGIN_REQUIRED: import.meta.env.PROD
    ? 'TRUE'
    : import.meta.env.VITE_LOGIN_REQUIRED,
  AIRTABLE_ACCESS_TOKEN: import.meta.env.VITE_AIRTABLE_ACCESS_TOKEN,
  AIRTABLE_HOST: import.meta.env.VITE_AIRTABLE_HOST,

  // Microsoft Login
  MS_CLIENT_ID: import.meta.env.VITE_MS_CLIENT_ID,
  MS_REDIRECT_URI: import.meta.env.VITE_MS_REDIRECT_URI,
  MS_LOGOUT_URI: import.meta.env.VITE_MS_LOGOUT_URI,
  MS_TENANT_ID: import.meta.env.VITE_MS_TENANT_ID,

  /*** USA ***/

  // Purchases USA
  USA_PURCHASES_BASE: import.meta.env.VITE_USA_PURCHASES_BASE,
  USA_PURCHASES_TABLE: import.meta.env.VITE_USA_PURCHASES_TABLE,
  // Sales USA
  USA_SALES_BASE: import.meta.env.VITE_USA_SALES_BASE,
  USA_COST_ANALYSIS_TABLE: import.meta.env.VITE_USA_COST_ANALYSIS_TABLE,
  USA_CA_PHASES_TABLE: import.meta.env.VITE_USA_CA_PHASES_TABLE,
  USA_CA_LABOR_DETAILS_TABLE: import.meta.env.VITE_USA_CA_LABOR_DETAILS_TABLE,
  USA_SITES_TABLE: import.meta.env.VITE_USA_SITES_TABLE,
  // Operations USA
  USA_OPERATIONS_BASE: import.meta.env.VITE_USA_OPERATIONS_BASE,
  USA_TRAVEL_TIMES_TABLE: import.meta.env.VITE_USA_TRAVEL_TIMES_TABLE,
  USA_WORKED_TIMES_TABLE: import.meta.env.VITE_USA_WORKED_TIMES_TABLE,
  USA_WAITING_TIMES_TABLE: import.meta.env.VITE_USA_WAITING_TIMES_TABLE,
  USA_PROJECTS_TABLE: import.meta.env.VITE_USA_PROJECTS_TABLE,
  USA_TIMES_BY_DAY_TABLE: import.meta.env.VITE_USA_TIMES_BY_DAY_TABLE,
  // People USA
  USA_PEOPLE_BASE: import.meta.env.VITE_USA_PEOPLE_BASE,
  USA_PAYROLL_TABLE: import.meta.env.VITE_USA_PAYROLL_TABLE,

  /*** MEX ***/

  // Purchases MEX
  MEX_PURCHASES_BASE: import.meta.env.VITE_MEX_PURCHASES_BASE,
  MEX_PURCHASES_TABLE: import.meta.env.VITE_MEX_PURCHASES_TABLE,
  // Sales MEX
  MEX_SALES_BASE: import.meta.env.VITE_MEX_SALES_BASE,
  MEX_COST_ANALYSIS_TABLE: import.meta.env.VITE_MEX_COST_ANALYSIS_TABLE,
  MEX_CA_PHASES_TABLE: import.meta.env.VITE_MEX_CA_PHASES_TABLE,
  MEX_CA_LABOR_DETAILS_TABLE: import.meta.env.VITE_MEX_CA_LABOR_DETAILS_TABLE,
  MEX_SITES_TABLE: import.meta.env.VITE_MEX_SITES_TABLE,
  // Operations MEX
  MEX_OPERATIONS_BASE: import.meta.env.VITE_MEX_OPERATIONS_BASE,
  MEX_PROJECTS_TABLE: import.meta.env.VITE_MEX_PROJECTS_TABLE,
  // People MEX
  MEX_PEOPLE_BASE: import.meta.env.VITE_MEX_PEOPLE_BASE,
  MEX_PAYROLL_TABLE: import.meta.env.VITE_MEX_PAYROLL_TABLE,

  /*** BRL ***/

  // Purchases BRL
  BRL_PURCHASES_BASE: import.meta.env.VITE_BRL_PURCHASES_BASE,
  BRL_PURCHASES_TABLE: import.meta.env.VITE_BRL_PURCHASES_TABLE,
  // Sales BRL
  BRL_SALES_BASE: import.meta.env.VITE_BRL_SALES_BASE,
  BRL_COST_ANALYSIS_TABLE: import.meta.env.VITE_BRL_COST_ANALYSIS_TABLE,
  BRL_CA_PHASES_TABLE: import.meta.env.VITE_BRL_CA_PHASES_TABLE,
  BRL_CA_LABOR_DETAILS_TABLE: import.meta.env.VITE_BRL_CA_LABOR_DETAILS_TABLE,
  BRL_SITES_TABLE: import.meta.env.VITE_BRL_SITES_TABLE,
  // Operations BRL
  BRL_OPERATIONS_BASE: import.meta.env.VITE_BRL_OPERATIONS_BASE,
  BRL_PROJECTS_TABLE: import.meta.env.VITE_BRL_PROJECTS_TABLE,
  // People BRL
  BRL_PEOPLE_BASE: import.meta.env.VITE_BRL_PEOPLE_BASE,
  BRL_PAYROLL_TABLE: import.meta.env.VITE_BRL_PAYROLL_TABLE,
};
